// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRT.Complaint.Data;

#nullable disable

namespace SRT.Complaint.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528025909_SeedSubCategories")]
    partial class SeedSubCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SRT.Complaint.Models.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedIps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RateLimitPerMin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RevokedById")
                        .HasColumnType("int");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RevokedById");

                    b.ToTable("ApiKeys", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ApiKeyScope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiKeyId")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.ToTable("ApiKeyScopes", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ApiRequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApiKeyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QueryString")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ResponseMs")
                        .HasColumnType("int");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId", "CreatedAt");

                    b.ToTable("ApiRequestLogs", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActorCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ActorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("AuditLogs", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Web");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalSystem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("IncidentDate")
                        .HasColumnType("date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReporterEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReporterIdCard")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReporterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReporterPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SatisfactionNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte?>("SatisfactionScore")
                        .HasColumnType("tinyint");

                    b.Property<bool>("SlaBreached")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SlaDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectStation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("ExternalSystem", "ExternalId")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL");

                    b.ToTable("Complaints", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ComplaintAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintAttachments", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ComplaintCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultPriority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ComplaintCategories", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultPriority = "Normal",
                            DepartmentName = "ฝ่ายการเดินรถ",
                            IsActive = true,
                            Name = "ความตรงต่อเวลา",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            DefaultPriority = "Normal",
                            DepartmentName = "ฝ่ายการโดยสาร",
                            IsActive = true,
                            Name = "บริการบนขบวนรถ",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            DefaultPriority = "Normal",
                            DepartmentName = "ฝ่ายบริหารทรัพยากรบุคคล",
                            IsActive = true,
                            Name = "พนักงาน / มารยาท",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            DefaultPriority = "Normal",
                            DepartmentName = "ฝ่ายโยธา",
                            IsActive = true,
                            Name = "สิ่งอำนวยความสะดวก",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            DefaultPriority = "Normal",
                            DepartmentName = "ฝ่ายบริการสถานี",
                            IsActive = true,
                            Name = "ความสะอาด",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            DefaultPriority = "High",
                            DepartmentName = "ฝ่ายการพาณิชย์",
                            IsActive = true,
                            Name = "ตั๋ว / การคืนเงิน",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            DefaultPriority = "Urgent",
                            DepartmentName = "ฝ่ายรักษาความปลอดภัย",
                            IsActive = true,
                            Name = "ความปลอดภัย",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            DefaultPriority = "Normal",
                            DepartmentName = "ฝ่ายบริการสถานี",
                            IsActive = true,
                            Name = "สถานี / ที่จอดรถ",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            DefaultPriority = "Normal",
                            IsActive = true,
                            Name = "อื่น ๆ",
                            SortOrder = 9
                        });
                });

            modelBuilder.Entity("SRT.Complaint.Models.ComplaintNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintNotes", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ComplaintSubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ComplaintSubCategories", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "รถออกล่าช้า",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "รถมาถึงล่าช้า",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "ยกเลิกขบวนโดยไม่แจ้งล่วงหน้า",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "หยุดกลางทางนานผิดปกติ",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "เวลาจอดสถานีไม่ตรงตารางเวลา",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "ที่นั่ง / เตียงชำรุด",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "แอร์ / พัดลมไม่ทำงาน",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "ห้องน้ำบนขบวนชำรุด / สกปรก",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "บริการอาหารและเครื่องดื่ม",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "เต้ารับไฟฟ้าชำรุด",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Wi-Fi / ระบบบันเทิงขัดข้อง",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "พูดจาไม่สุภาพ / ไม่ให้เกียรติ",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "บริการล่าช้า / ไม่ใส่ใจ",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "ให้ข้อมูลผิด / ไม่ถูกต้อง",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "พฤติกรรมไม่เหมาะสม",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "เลือกปฏิบัติ",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "ลิฟต์ / บันไดเลื่อนขัดข้อง",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "ที่นั่งรอในสถานีชำรุด",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "สิ่งอำนวยความสะดวกสำหรับผู้พิการ",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "ป้ายบอกทาง / ข้อมูลไม่ชัดเจน",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "ระบบประกาศเสียงขัดข้อง",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "ความสะอาดในขบวนรถ",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "ความสะอาดในสถานี",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "ห้องน้ำสกปรก",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "การกำจัดขยะ",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "ปัญหาการจองตั๋ว",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "ขอคืนเงินค่าตั๋ว",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "ราคาตั๋วไม่ถูกต้อง",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "ระบบออนไลน์ขัดข้อง",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "ปัญหาโปรโมชั่น / ส่วนลด",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 7,
                            IsActive = true,
                            Name = "การโจรกรรม / ทรัพย์สินสูญหาย",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 7,
                            IsActive = true,
                            Name = "การล่วงละเมิด / คุกคาม",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 7,
                            IsActive = true,
                            Name = "ผู้โดยสารก่อกวน / พฤติกรรมน่ารังเกียจ",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 7,
                            IsActive = true,
                            Name = "อุบัติเหตุในบริเวณสถานี",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 7,
                            IsActive = true,
                            Name = "การลักลอบนำสิ่งของอันตราย",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 8,
                            IsActive = true,
                            Name = "ที่จอดรถไม่เพียงพอ",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 8,
                            IsActive = true,
                            Name = "ค่าจอดรถไม่ถูกต้อง",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 8,
                            IsActive = true,
                            Name = "สิ่งก่อสร้างกีดขวาง / ทางเข้าออก",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 8,
                            IsActive = true,
                            Name = "ไฟส่องสว่างไม่เพียงพอ",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 9,
                            IsActive = true,
                            Name = "ข้อเสนอแนะทั่วไป",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 9,
                            IsActive = true,
                            Name = "ไม่อยู่ในหมวดหมู่ข้างต้น",
                            SortOrder = 2
                        });
                });

            modelBuilder.Entity("SRT.Complaint.Models.ComplaintTerms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedById");

                    b.ToTable("ComplaintTerms", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ComplaintTransferLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplaintId")
                        .HasColumnType("int");

                    b.Property<int?>("FromOfficerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAutoAssign")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ToOfficerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransferredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("FromOfficerId");

                    b.HasIndex("ToOfficerId");

                    b.ToTable("ComplaintTransferLog", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ContentBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.ToTable("ContentBlocks", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ExternalSyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("int");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FetchedCount")
                        .HasColumnType("int");

                    b.Property<int>("NewCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TriggeredById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredById");

                    b.ToTable("ExternalSyncLogs", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEmailEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LabelTh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SmsBody")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventKey")
                        .IsUnique();

                    b.ToTable("NotificationTemplates", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailSubject = "[รฟท.] รับเรื่องร้องเรียนของท่านแล้ว เลขที่ {ReferenceNumber}",
                            EventKey = "ComplaintReceived",
                            IsEmailEnabled = true,
                            IsSmsEnabled = true,
                            LabelTh = "รับเรื่องร้องเรียนแล้ว",
                            SmsBody = "[รฟท.] รับเรื่องร้องเรียนของท่านแล้ว เลขที่ {ReferenceNumber} ติดตามสถานะ: {TrackingUrl}"
                        },
                        new
                        {
                            Id = 2,
                            EmailSubject = "[รฟท.] อัปเดตสถานะเรื่องร้องเรียน {ReferenceNumber}",
                            EventKey = "StatusChanged",
                            IsEmailEnabled = true,
                            IsSmsEnabled = true,
                            LabelTh = "สถานะเรื่องเปลี่ยนแปลง",
                            SmsBody = "[รฟท.] เรื่อง {ReferenceNumber} อัปเดตสถานะเป็น: {Status}"
                        },
                        new
                        {
                            Id = 3,
                            EmailSubject = "[รฟท.] เรื่องร้องเรียน {ReferenceNumber} ได้รับการแก้ไขแล้ว",
                            EventKey = "ComplaintClosed",
                            IsEmailEnabled = true,
                            IsSmsEnabled = true,
                            LabelTh = "ปิดเรื่องร้องเรียนแล้ว",
                            SmsBody = "[รฟท.] เรื่อง {ReferenceNumber} ปิดแล้ว ขอบคุณที่ใช้บริการ"
                        },
                        new
                        {
                            Id = 4,
                            EmailSubject = "[รฟท.] มอบหมายเรื่องร้องเรียนให้ท่าน {ReferenceNumber}",
                            EventKey = "AutoAssigned",
                            IsEmailEnabled = true,
                            IsSmsEnabled = false,
                            LabelTh = "มอบหมายเรื่องอัตโนมัติ"
                        },
                        new
                        {
                            Id = 5,
                            EmailSubject = "[รฟท.] เตือน: เรื่อง {ReferenceNumber} ใกล้ครบกำหนด SLA",
                            EventKey = "SlaWarning",
                            IsEmailEnabled = true,
                            IsSmsEnabled = false,
                            LabelTh = "เตือน SLA ใกล้ครบกำหนด"
                        },
                        new
                        {
                            Id = 6,
                            EmailSubject = "[รฟท.] แจ้งเตือน: เรื่อง {ReferenceNumber} เกิน SLA แล้ว",
                            EventKey = "SlaBreached",
                            IsEmailEnabled = true,
                            IsSmsEnabled = false,
                            LabelTh = "SLA เกินกำหนดแล้ว"
                        },
                        new
                        {
                            Id = 7,
                            EmailSubject = "[รฟท.] เร่งด่วน: รับเรื่องร้องเรียนระดับ Critical {ReferenceNumber}",
                            EventKey = "CriticalReceived",
                            IsEmailEnabled = true,
                            IsSmsEnabled = false,
                            LabelTh = "รับเรื่องเร่งด่วนมาก"
                        },
                        new
                        {
                            Id = 8,
                            EmailSubject = "[รฟท.] แจ้งเตือน: มีการขอดูข้อมูลผู้แจ้ง {ReferenceNumber}",
                            EventKey = "DecryptionRequested",
                            IsEmailEnabled = true,
                            IsSmsEnabled = false,
                            LabelTh = "ขอดูข้อมูลผู้แจ้งทุจริต"
                        });
                });

            modelBuilder.Entity("SRT.Complaint.Models.SlaConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutoAssignAfterHours")
                        .HasColumnType("int");

                    b.Property<string>("LabelTh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ResolutionHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<int>("WarningThresholdPercent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Priority")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.ToTable("SlaConfigs", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoAssignAfterHours = 1,
                            LabelTh = "เร่งด่วนมาก (ความปลอดภัย)",
                            Priority = "Critical",
                            ResolutionHours = 24,
                            UpdatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningThresholdPercent = 80
                        },
                        new
                        {
                            Id = 2,
                            AutoAssignAfterHours = 4,
                            LabelTh = "เร่งด่วน",
                            Priority = "Urgent",
                            ResolutionHours = 72,
                            UpdatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningThresholdPercent = 80
                        },
                        new
                        {
                            Id = 3,
                            AutoAssignAfterHours = 8,
                            LabelTh = "สำคัญ",
                            Priority = "High",
                            ResolutionHours = 120,
                            UpdatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningThresholdPercent = 80
                        },
                        new
                        {
                            Id = 4,
                            AutoAssignAfterHours = 12,
                            LabelTh = "ปกติ",
                            Priority = "Normal",
                            ResolutionHours = 168,
                            UpdatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningThresholdPercent = 80
                        },
                        new
                        {
                            Id = 5,
                            AutoAssignAfterHours = 24,
                            LabelTh = "ข้อเสนอแนะ",
                            Priority = "Low",
                            ResolutionHours = 360,
                            UpdatedAt = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WarningThresholdPercent = 80
                        });
                });

            modelBuilder.Entity("SRT.Complaint.Models.StaffUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .IsFixedLength();

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("TempPasswordEncrypted")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("TempPasswordExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.ToTable("StaffUsers", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.Webhook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiKeyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Events")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LastStatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.ToTable("Webhooks", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.WebhookDeliveryLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte>("AttemptCount")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("int");

                    b.Property<int>("WebhookId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WebhookId");

                    b.ToTable("WebhookDeliveryLogs", "dbo");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ApiKey", b =>
                {
                    b.HasOne("SRT.Complaint.Models.StaffUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SRT.Complaint.Models.StaffUser", "RevokedBy")
                        .WithMany()
                        .HasForeignKey("RevokedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");

                    b.Navigation("RevokedBy");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ApiKeyScope", b =>
                {
                    b.HasOne("SRT.Complaint.Models.ApiKey", "ApiKey")
                        .WithMany("Scopes")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ApiRequestLog", b =>
                {
                    b.HasOne("SRT.Complaint.Models.ApiKey", "ApiKey")
                        .WithMany("RequestLogs")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("SRT.Complaint.Models.AuditLog", b =>
                {
                    b.HasOne("SRT.Complaint.Models.StaffUser", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("SRT.Complaint.Models.Complaint", b =>
                {
                    b.HasOne("SRT.Complaint.Models.StaffUser", "AssignedTo")
                        .WithMany("AssignedComplaints")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRT.Complaint.Models.ComplaintCategory", "Category")
                        .WithMany("Complaints")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRT.Complaint.Models.ComplaintSubCategory", "SubCategory")
                        .WithMany("Complaints")
                        .HasForeignKey("SubCategoryId");

                    b.Navigation("AssignedTo");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ComplaintAttachment", b =>
                {
                    b.HasOne("SRT.Complaint.Models.Complaint", "Complaint")
                        .WithMany("Attachments")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ComplaintNote", b =>
                {
                    b.HasOne("SRT.Complaint.Models.StaffUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("SRT.Complaint.Models.Complaint", "Complaint")
                        .WithMany("Notes")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ComplaintSubCategory", b =>
                {
                    b.HasOne("SRT.Complaint.Models.ComplaintCategory", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ComplaintTerms", b =>
                {
                    b.HasOne("SRT.Complaint.Models.StaffUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ComplaintTransferLog", b =>
                {
                    b.HasOne("SRT.Complaint.Models.Complaint", "Complaint")
                        .WithMany("TransferLogs")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRT.Complaint.Models.StaffUser", "FromOfficer")
                        .WithMany()
                        .HasForeignKey("FromOfficerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRT.Complaint.Models.StaffUser", "ToOfficer")
                        .WithMany()
                        .HasForeignKey("ToOfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complaint");

                    b.Navigation("FromOfficer");

                    b.Navigation("ToOfficer");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ContentBlock", b =>
                {
                    b.HasOne("SRT.Complaint.Models.StaffUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ExternalSyncLog", b =>
                {
                    b.HasOne("SRT.Complaint.Models.StaffUser", "TriggeredBy")
                        .WithMany()
                        .HasForeignKey("TriggeredById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TriggeredBy");
                });

            modelBuilder.Entity("SRT.Complaint.Models.SlaConfig", b =>
                {
                    b.HasOne("SRT.Complaint.Models.StaffUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("SRT.Complaint.Models.Webhook", b =>
                {
                    b.HasOne("SRT.Complaint.Models.ApiKey", "ApiKey")
                        .WithMany("Webhooks")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("SRT.Complaint.Models.WebhookDeliveryLog", b =>
                {
                    b.HasOne("SRT.Complaint.Models.Webhook", "Webhook")
                        .WithMany("DeliveryLogs")
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ApiKey", b =>
                {
                    b.Navigation("RequestLogs");

                    b.Navigation("Scopes");

                    b.Navigation("Webhooks");
                });

            modelBuilder.Entity("SRT.Complaint.Models.Complaint", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Notes");

                    b.Navigation("TransferLogs");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ComplaintCategory", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("SRT.Complaint.Models.ComplaintSubCategory", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("SRT.Complaint.Models.StaffUser", b =>
                {
                    b.Navigation("AssignedComplaints");
                });

            modelBuilder.Entity("SRT.Complaint.Models.Webhook", b =>
                {
                    b.Navigation("DeliveryLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
